package
{
	

	public class DefineClass
	{
		public function DefineClass()
		{
			
		}
		
		public static function init():void
		{
			zGroupNameEffectMauBinh;
			zBackground;
			zAlertWindow;
			zBackgroundButtonForm_1;
			zBackgroundButtonForm_2;
			zConfirmWindow;
			zEffectText_1;
			MyriadPro_2;
			zChooseChannelScreen;
			zLoginWindow;
			zLoadingScreen;
			zCreateRoomWindow;
			zLobbyRoomScreen;
			zSearchRoomWindow;
			zAccuseWindow;
			zAvatarForm_1;
			zAvatarForm_2;
			zChatBox_1;
			zConfirmFullDeckWindow;
			zContextMenu;
			zInvitePlayWindow;
			zPlayingScreen;
			zPlayingScreenMauBinh;
			zPlayingScreenXito;
			zPlayUserProfileForm_1;
			zPlayUserProfileForm_2;
			zPlayUserProfileForm_3;
			zPlayUserProfileForm_4;
			zPlayUserProfileForm_1_Phom;
			zPlayUserProfileForm_2_Phom;
			zPlayUserProfileForm_3_Phom;
			zPlayUserProfileForm_4_Phom;
			zPlayUserProfileForm_1_MauBinh;
			zPlayUserProfileForm_2_MauBinh;
			zPlayUserProfileForm_3_MauBinh;
			zPlayUserProfileForm_4_MauBinh;
			zPlayUserProfileForm_1_Xito;
			zPlayUserProfileForm_2_Xito;
			zPlayUserProfileForm_3_Xito;
			zPlayUserProfileForm_4_Xito;
			zReadyButton;
			zResultWindow;
			zResultWindowMauBinh;
			zResultWindowXito;
			zScoreWindow;
			zStartButton;
			zTimeBar_1;
			zTimeBar_2;
			zTimeBar_3;
			zTimeBarCircle
			zCompensateAllEffect;
			zFullDeckEffect;
			zNoDeckEffect;
			zNoRelationshipEffect;
			zWinEffect;
			zCard;
			zCardPhom;
			zCardMauBinh;
			zCardManagerMauBinh;
			zLoadingWindow;
			zWhiteWinWindow;
			zSelectGameWindow;
			zOrderCardWindow;
			zClock;
			zGroupNameBar;
			zGroupNameEffectMauBinh;
			zRegisterWindow;
			zAddMoneyWindow;
			zForgetPassWindow;
			zTopMenu;
			zAvatarForm_3;
			zFillNameWindow;
			zBubbleChat;
			zMyComboBox;
			zOrderCardWindow;
			zUserProfileWindow;
			zGroupResultEffect;
		}
	}
}