package
{
	

	public class DefineClass
	{
		public function DefineClass()
		{
			
		}
		
		public static function init():void
		{
			zGroupNameEffectMauBinh;
			zBackground;
			zAlertWindow;
			zBackgroundButtonForm_1;
			zBackgroundButtonForm_2;
			zConfirmWindow;
			zEffectText_1;
			MyriadPro_2;
			zChooseChannelScreen;
			zLoginWindow;
			zCreateRoomWindow;
			zLobbyRoomScreen;
			zSearchRoomWindow;
			zAvatarForm_1;
			zConfirmFullDeckWindow;
			zInvitePlayWindow;
			zPlayingScreenMauBinh;
			zPlayingScreenPhom;
			zPlayingScreenXito;
			zPlayUserProfileForm_1_Phom;
			zPlayUserProfileForm_2_Phom;
			zPlayUserProfileForm_3_Phom;
			zPlayUserProfileForm_4_Phom;
			zPlayUserProfileForm_1_MauBinh;
			zPlayUserProfileForm_2_MauBinh;
			zPlayUserProfileForm_3_MauBinh;
			zPlayUserProfileForm_4_MauBinh;
			zPlayUserProfileForm_1_Xito;
			zPlayUserProfileForm_2_Xito;
			zPlayUserProfileForm_3_Xito;
			zPlayUserProfileForm_4_Xito;
			zReadyButton;
			zResultWindowMauBinh;
			zResultWindowXito;
			zStartButton;
			zCompensateAllEffect;
			zFullDeckEffect;
			zNoDeckEffect;
			zNoRelationshipEffect;
			zWinEffect;
			zCardPhom;
			zCardMauBinh;
			zCardManagerMauBinh;
			zLoadingWindow;
			zSelectGameWindow;
			zOrderCardWindow;
			zClock;
			zGroupNameBar;
			zRegisterWindow;
			zAddMoneyWindow;
			zAddMoneyWindow2;
			zForgetPassWindow;
			zTopMenu;
			zFillNameWindow;
			zMyComboBox;
			zOrderCardWindow;
			zUserProfileWindow;
			zGroupResultEffect;
			zComboBoxRow;
			zSlideBar;
			zAddFriendWindow;
			zChannelList;
			zChannelRow;
			zCardManagerPhom;
			zTimeBar_1_Phom;
			zSendMessageWindow;
			zAirFullDeckEffect;
			zFinishFullDeckEffect;
			zResultWindowPhom;
			zBubbleChat;
			Emo;
			Emo1;
			Emo2;
			Emo3;
			Emo4;
			Emo5;
			Emo6;
			Emo7;
			Emo8;
			Emo9;
			Emo10;
			Emo11;
			Emo12;
			Emo13;
			Emo14;
			Emo15;
			Emo16;
			
			MyInfoTlmnMc;
			MyClock;
			PlayerInfoTlmnMc;
			PlayScreenTlmnMc;
			MyAvatar;
			MyCard;
			MyCardDeck;
			
			Shop_Coffer_Item_Mc;
			ContentAvatarMc;
			ContentGiftMc;
			ContentGoldMc;
			ContentItemMc;
			ContentTourMc;
			ContentMyAvatarMc;
			ContentMyItemGoldMc;
			ContentMyItemNormalMc;
			ContentMyGiftMc;
			ContentMyTourMc;
			ChoosePayMoneyTypeMc;
			zSystemNoticeBar;
			ContentUserTopList;
			BuyTourSuccessMc;
			TutorialAddMoneyPopup;
			AgreeChangeGiftPopup;
			
			BoGameBaiMainView;
			zGiftCodeWindow;
			zCloseConnectionWindow;
			AddMoneySuccessWindow;
			BuyItemUnSuccessWindown;
		}
	}
}